// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace SlavStore.Data.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changeToUserItem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeToUserItem));
        
        string IMigrationMetadata.Id
        {
            get { return "201705011301544_changeToUserItem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
